Contrast-Security-OSS/vulnpy

.flake8
.github/workflows/main.yml
.gitignore
README.md
pyproject.toml
setup.py
src/vulnpy/flask/__init__.py
src/vulnpy/flask/blueprint.py
src/vulnpy/trigger/cmdi.py
tests/flask/test_blueprint.py
tests/trigger/test_cmdi.py
tox.ini

This contains the initial setup for vulnpy, which is the Python equivalent of vulneruby/vulneruby_engine.
Here's what I **did** accomplish in this PR:
- set up vulnpy as a pip-installable python package
- added lint checks and pipeline checks, with github actions
- added vulnerable CMDi functions for `os.system` and `subprocess.Popen`
- added a vulnerable Flask blueprint that uses these vulnerable functions
- corresponding agent PR is inbound
I made a bunch of tickets for future work, because this has taken quite a while and I need to move on. These are:
- PYT-894-896: add django, pyramid, flask
- PYT-897: add sharable templates
- PYT-898-901: create screener apps for each framework using these endpoints
In the above list, the tickets in each bullet point are blockers for the subsequent …

PYT-674 Set up repo; Add cmdi triggers and Flask endpoints

---

.github/workflows/main.yml
README.md
setup.py
src/vulnpy/pyramid/vulnerable_routes.py
tests/pyramid/test_vulnerable_routes.py

- provides the initial setup for including vulnpy endpoints in a Pyramid application
- adds basic cmdi endpoints for os.system and subprocess.Popen
- we're already starting to see some duplication in the vulnpy testing suite. I'm brainstorming ways that we can write common tests - this will also ensure that the API exposed for all frameworks is exactly the same
- I have the corresponding apptests ready to go. As soon as this goes through I'll PR to the agent

Pyramid setup + cmdi

---

README.md
setup.py
src/vulnpy/falcon/__init__.py
src/vulnpy/falcon/vulnerable.py
src/vulnpy/flask/blueprint.py
src/vulnpy/pyramid/vulnerable_routes.py
src/vulnpy/trigger/cmdi.py
tests/falcon/test_vulnerable.py
tests/flask/test_blueprint.py
tests/pyramid/test_vulnerable_routes.py
tests/trigger/test_cmdi.py

- This contains the skeleton for pluggable falcon endpoints. Falcon doesn't have a blueprint-like functionality like most other frameworks, so I created a function in `vulnpy` for adding our routes to the falcon app.
- Added cmdi falcon routes
- based on some of the code from the falcon apptests, I was able to greatly simplify subprocess.Popen error handling in all frameworks. Basically, now we're using the `shell` mode for this trigger
- adds `mock` as a testing dependency

PYT-896 Add Falcon cmdi

---

.gitignore
CONTRIBUTING.md
MANIFEST.in
Makefile
README.md
apps/django_app.py
apps/falcon_app.py
apps/flask_app.py
apps/pyramid_app.py
scripts/gen_templates.sh
setup.py
src/vulnpy/common/__init__.py
src/vulnpy/common/templating.py
src/vulnpy/common/utils.py
src/vulnpy/django/vulnerable.py
src/vulnpy/falcon/vulnerable.py
src/vulnpy/flask/blueprint.py
src/vulnpy/pyramid/vulnerable_routes.py
src/vulnpy/templates/cmdi.html
src/vulnpy/templates/fragments/base.html
src/vulnpy/templates/fragments/cmdi.frag.html
src/vulnpy/templates/fragments/home.frag.html
src/vulnpy/templates/home.html
tests/django/test_vulnerable.py
tests/falcon/test_vulnerable.py
tests/flask/test_blueprint.py
tests/pyramid/test_vulnerable_routes.py

- Added HTML responses to all endpoints
- The HTML does not require a template engine, so it is fully reusable across apps
- caveat: we can't make use of code deduplication that comes naturally from templates - instead we're auto-generating full HTML pages using HTML fragments. These fragments are partial webpages that are spliced into the master navigation template using `make`
- Added tiny (single-file!) webapps for each supported framework
- These tiny apps can be served using `make (flask|falcon|pyramid|pylons)`
- This leads naturally into display apps, etc. I hope to dockerize them eventually.
- Slightly changed the way we add vulnpy to pyramid applications
- This is a breaking change, and I have the agent PR ready with all tests passing locally
- as soon as this is merged, I will …

Pyt 897 add templates

---

Makefile
apps/django_app.py
apps/falcon_app.py
apps/flask_app.py
apps/pyramid_app.py

*Minor adjustments to make vulnpy sample apps compatible with screener*
- Added the ability to start each sample app with contrast enabled
- This is controlled by setting `VULNPY_USE_CONTRAST`
- Added the ability to customize host and port for each app
- For example: `make flask HOST=0.0.0.0 PORT=7000`

PYT-898 PYT-899 PYT-900 PYT-901 Set up sample apps for screener

---

CONTRIBUTING.md
src/vulnpy/django/vulnerable.py
src/vulnpy/falcon/vulnerable.py
src/vulnpy/flask/blueprint.py
src/vulnpy/pyramid/vulnerable_routes.py
src/vulnpy/trigger/__init__.py
src/vulnpy/trigger/util.py
tests/trigger/test_trigger.py

This PR seeks to make adding new triggers to vulnpy easier by automating each framework's view generation.
This is certainly not final and can use more work later on, but this is a good stopping point. I also did consider deduping some of the inter-framework code similarities, but I decided against it right now. A class could help, but I think that would add more complexity than it merits. Right now each framework does its own tiny different thing in its own file - let's not make it more complicated for now.

Automate generating framework endpoints

---

CONTRIBUTING.md
src/vulnpy/trigger/__init__.py
tests/__init__.py
tests/django/test_vulnerable.py
tests/falcon/test_vulnerable.py
tests/flask/test_blueprint.py
tests/pyramid/test_vulnerable_routes.py
tests/trigger/base_test.py
tests/trigger/test_cmdi.py
tests/trigger/test_deserialization.py
tests/trigger/test_unsafe_code_exec.py

Consolidate unit tests to not require adding new framework tests when new triggers are added.
* We could dedupe some of the framework tests even more (django and flask share some methods) but it seemed overkill at this time
* we can't really automate tests under trigger/ as these are very custom. These tests themselves are a tiny bit overkill (we don't need to test the actual call to the trigger), but it's worth keeping high coverage. So for these tests the goal was to create an interface to make it very clear how to add new trigger tests (by inheriting BaseTriggerTest) and guide the developer.
* I removed some testing I don't think we need - framework tests checked for bad inputs given and so did trigger tests.

Pyt 992 consolidate testing

---

CONTRIBUTING.md
src/vulnpy/django/vulnerable.py
src/vulnpy/falcon/vulnerable.py
src/vulnpy/flask/blueprint.py
src/vulnpy/pyramid/vulnerable_routes.py
src/vulnpy/templates/cmdi.html
src/vulnpy/templates/deserialization.html
src/vulnpy/templates/fragments/base.html
src/vulnpy/templates/fragments/xss.frag.html
src/vulnpy/templates/home.html
src/vulnpy/templates/unsafe_code_exec.html
src/vulnpy/templates/xss.html
src/vulnpy/trigger/__init__.py
src/vulnpy/trigger/xss.py
tests/django/test_vulnerable.py
tests/falcon/test_vulnerable.py
tests/flask/test_blueprint.py
tests/pyramid/test_vulnerable_routes.py
tests/trigger/test_xss.py

Vulnpy can now detect if user input is injected into the response content / body for any of the supported frameworks.
Note that xss does not follow the same pattern as other trigger functions; it doesn't have a trigger function. I considered defining `do_raw`  as
```
def do_raw(user_input):
template = get_template("{}.html".format(name))
if name == "xss" and trigger == "raw":
template += "<p>XSS: " + user_input + "</p>"
return template
```
but that seemed to cross the line of separation of concerns between triggers and templates. I think the current way makes sense.

Add raw reflected xss support

---

src/vulnpy/flask/blueprint.py
tests/falcon/test_vulnerable.py
tox.ini

- pin black version
- revert changes made with a newer version of the linter to get unit tests to pass

PYT-1040 Pin black to 19.10b0

---

src/vulnpy/templates/cmdi.html
src/vulnpy/templates/deserialization.html
src/vulnpy/templates/fragments/base.html
src/vulnpy/templates/fragments/sqli.frag.html
src/vulnpy/templates/hash.html
src/vulnpy/templates/home.html
src/vulnpy/templates/rand.html
src/vulnpy/templates/sqli.html
src/vulnpy/templates/ssrf.html
src/vulnpy/templates/unsafe_code_exec.html
src/vulnpy/templates/xss.html
src/vulnpy/templates/xxe.html
src/vulnpy/trigger/__init__.py
src/vulnpy/trigger/sqli.py
tests/trigger/test_sqli.py

This adds triggers for sqlite3 `execute*` methods. I don't think full database + ORM coverage belongs here, but let me know if you think otherwise. Keeping the sqlite3 database in-memory vastly simplifies these new triggers.
I played around with a sort of weird functional design here, which was kind of fun.

PYT-1000 Add sqli

---

setup.py

Even though we're using `mock` in the SSRF triggers, I forgot to move it from `extra` requirements to real package requirements. This fixes that

Make mock a real requirement

---

setup.py

For frameworks we don't directly support here (yet), this provides users with an option to install all trigger dependencies only. This will allow consumers to use `vulnpy.trigger` modules directly without installing any particular framework dependencies.

Add trigger extras install option

---

Makefile
README.md
apps/wsgi_app.py
setup.py
src/vulnpy/wsgi/__init__.py
src/vulnpy/wsgi/app.py
tests/wsgi/test_app.py

This PR adds a pure WSGI application to vulnpy. This works a little differently from using a real framework, since routes aren't registered ahead of time - instead, on each request we parse PATH_INFO and delegate to a trigger function accordingly.
To test this out live, stand up the WSGI app with `make wsgi`.

Add WSGI support

---

setup.py

pipeline that fails like this
```
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install lxml==4.6.1 and vulnpy[flask]==0.1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested lxml==4.6.1
vulnpy[flask] 0.1.0 depends on lxml==4.3.1; extra == "flask"
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
this should allow for flexibility.

change lxml version for flexibility

---

.flake8
.gitignore
Dockerfile
Makefile
README.md
setup.py

* Adds a Dockerfile and instructions to the README. This file creates an image that can be used to run any of our sample webservers
* Made some assorted cleanup to build-related files during this process
* The exact architecture / location of the Dockerfile may change very soon, since we'll be using this for internal testing and development
* If you want to test this for yourself, follow the new instructions in the README

Add Dockerfile for contrast-instrumented webservers

---

Dockerfile
README.md

We don't get route coverage in `wsgi`, so it's not a great default framework here. In my opinion, flask has the best server logs, so I went with that instead.
I also rearranged the Dockerfile a little to reduce build times when iterating on `vulnpy`.

Update Dockerfile to use flask by default

---

src/vulnpy/trigger/sqli.py

While creating `db_connection` only once seems clean and works with pytest, actually running a live app fails with `ProgrammingError: SQLite objects created in a thread can only be used in that same thread`. suggested solution [here](https://stackoverflow.com/questions/48218065/programmingerror-sqlite-objects-created-in-a-thread-can-only-be-used-in-that-sa) is to create the connection when you're going to use it.
Tested both live and in pytest and it works as I would expect.

make connection in the same thread

---

apps/flask_app.py

This adds secure cookie missing and httponly vulns to the flask app in vulnpy. The app is already vulnerable to session timeout without any further configuration.

Add session cookie config vulns to flask app

---

apps/bottle_app.py

We were missing host/port values when running a live app so it was using bottle's defaults.

get host/port for bottle

---

setup.py

pinning versions
- framework versions are pinned to greatest major version currently supported by the contrast agent
- other versions I pinned to prevent failures, we can up them later
to test, I created a new env and pip installed -e .[all], it worked!
```
Successfully installed Django-3.2 Flask-1.1.2 Jinja2-2.11.3 MarkupSafe-1.1.1 PasteDeploy-2.1.1 PyYAML-5.4.1 WebTest-2.0.35 Werkzeug-1.0.1 appdirs-1.4.4 asgiref-3.3.3 beautifulsoup4-4.9.3 bottle-0.12.19 click-7.1.2 distlib-0.3.1 falcon-2.0.0 filelock-3.0.12 gunicorn-20.1.0 hupper-1.10.2 itsdangerous-1.1.0 lxml-4.6.3 mock-3.0.5 packaging-20.9 plaster-1.0 plaster-pastedeploy-0.7 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pyramid-1.10.8 pytz-2021.1 six-1.15.0 soupsieve-2.2.1 sqlparse-0.4.1 toml-0.10.2 tox-3.23.0 translationstring-1.4 …
```

pin dependency versions

---

setup.py

this passed my local tests. I think using `<` makes sense here because it's still quite permissive for other dependencies but prevents major version bumps from getting out of control.
We might have to iterate again, but hopefully not

Set max major version for framework dependencies

---

Makefile

Gunicorn times out by default after a while. This is very inconvenient for debugging with Pdb, since eventually gunicorn will kill the worker that was handling the request. This PR removes this behavior for the gunicorn-served falcon app

Remove gunicorn timeout

---

setup.py

As part of adding support for Flask 2.X we need to make sure vulnpy uses the correct version. If we do not add support when running the Flask 2.X framework tests we get this error:
```
ERROR: Cannot install Flask==2.0.0 and vulnpy[flask]==0.1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested Flask==2.0.0
vulnpy[flask] 0.1.0 depends on Flask<2; extra == "flask"
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

PYT-1556 vulnpy now installs flask versions less than 3

---

src/vulnpy/flask/blueprint.py
tests/flask/test_blueprint.py

This adds the ability to accept user input from a header named user-input. 
The purpose of this change was to test the source tracking changes made as part of this ticket: https://contrast.atlassian.net/browse/PYT-1547

PYT-1547 added User-Input header to send data to a trigger

---

.github/workflows/main.yml
setup.py
src/vulnpy/trigger/__init__.py
tests/falcon/test_vulnerable.py

Just like with flask 2 support we need to update the minimum required version for falcon.
Heres the error message I got when running installation steps locally:
```
Collecting Falcon==3.0
Using cached falcon-3.0.0-cp39-cp39-macosx_10_14_x86_64.whl (2.1 MB)
Collecting pymongo==3.11.0
Using cached pymongo-3.11.0-cp39-cp39-macosx_10_9_x86_64.whl
Requirement already satisfied: falcon-multipart==0.2.0 in /Users/nicholasliccione/opt/miniconda3/envs/fw-test-falcon3-py39/lib/python3.9/site-packages (from vulnpy[falcon]->-r requirements-3.0.txt (line 4)) (0.2.0)
Requirement already satisfied: lxml>=4.3.1 in /Users/nicholasliccione/opt/miniconda3/envs/fw-test-falcon3-py39/lib/python3.9/site-packages (from vulnpy[falcon]->-r requirements-3.0.txt (line 4)) (4.6.3)
ERROR: Cannot install Falcon==3.0 …
```

PYT-1580 vulnpy now installs falcon versions less than 4

---

.github/workflows/main.yml
setup.py
src/vulnpy/trigger/__init__.py
tests/falcon/test_vulnerable.py

Had to roll back changes made for falcon 3 support due to integration test failures. 
I left the `sudo apt-get update` command because the pipeline failed due to it trying to install deps that didn't exist at the location it tried to install from.

Roll back falcon max version to <3

---

tests/trigger/base_test.py

Makes trigger unit tests more flexible by allowing tests to use a custom comparison operator.
Example use:
```
@property
def good_input(self):
return "echo hacked", int, isinstance
```
The third argument is a binary operator that takes the other two args as its args. It should return a boolean indicating whether the input produced some expected form of output. In the above example, `isinstance(os.system("echo hacked"), int)` is `True`

PYT-1586 Make good input test more flexible

---

Makefile
README.md
apps/bottle_app.py
apps/pyramid_app.py
apps/wsgi_app.py
setup.py

Almost all the contrast supported frameworks can use uwsgi right off the bat - the only changes needed to happen in the *_app.py files themselves to put the app initialization code outside of the if main check. I don't love it (I like the main check), but if I wanted to keep that I would've had to make a second file. Nah....
I ran every single existing app locally to make sure I didn't break anything.

add uwsgi serving for all frameworks and update code to make it work

---

Makefile
apps/fastapi_app.py

Allow a fastapi app to use contrast and makefile to get host/port
Contrast middleware API is not out yet, but I'm designing it separately. Currently it needs the `original_app` as an argument

fastapi allow for Contrast middleware

---

src/vulnpy/fastapi/vulnerable.py

FastAPI routing machinery to define the route name so not all routes have the same name.

define route name

---

Makefile
apps/django_app.py

_Lets us use gunicorn and uwsgi to start up the sample Django app_
Our django app wasn't exposing a WSGI application callable, because it was relying completely on django internals. As such, we couldn't use any server other than the default django server to start up this app. Here's what I did to make this work:
- added a call to `django.core.wsgi.get_wsgi_application`
- replaced the django-style middlewares with our django-wsgi middleware
- made some Makefile cleanups to reduce some duplication
I had to do a fair amount of trial and error to get this exactly right, but all of our integration tests passed (internal link: https://github.com/Contrast-Security-Inc/python-agent/runs/3537765004?check_suite_focus=true)

PYT-1697 Enable alternate WSGI servers for django app

---

Makefile
README.md
setup.py

- Adds `uwsgi-old` extra dependency option for uwsgi 2.0.14
- Removes `falcon` make target in favor of `falcon-gunicorn`. `make falcon` now produces a make error with a helpful message. I went back and forth on this, but since falcon doesn't have a dev server, it's required that users install a prod server explicitly. I wanted to avoid the case where a user tries `pip install .[falcon] && make falcon`, which would fail. This also makes falcon consistent with all other frameworks, which is useful for internal testing purposes

PYT-1635 Remove falcon make target in favor of falcon-gunicorn

---

Makefile

After conducting some research it seems like these two CLI options are commonly used with uWSGI. If `--master` is used, we also require `--lazy-apps` for the contrast python agent to work correctly. This PR updates our default uWSGI flags to include both `--master` and `--lazy-apps`.

Add --master and --lazy-apps to uwsgi CLI options

---

Makefile

After reading gunicorn’s docs and some examples from SOF. The best option related to forking is to use pre-fork mode (--preload). This mode initialise our code in a "master" process and then simply fork off worker processes to handle requests. 
Passing pipeline:
https://github.com/Contrast-Security-Inc/python-agent/actions/runs/1229423154

PYT-1648 Determine how to set forking / gUnicorn

---

setup.py

The pipeline is failing with gunicorn ==0.16.0 and passing with 0.16.1.
This is a version from 2012 so lmk if we should pin to this or upgrade it.
The Pipeline:
https://github.com/Contrast-Security-Inc/python-agent/runs/3611188080?check_suite_focus=true

PYT-1645 Create Gunicorn Test - Minimum Version

---

setup.py

Pin FastAPI back to 0.68 until we resolve issues with 0.70

Pin fastapi back to 0.86 for now

---

README.md

Update the readme file to display `https` in the git clone url instead of `git`.

PYT-1903 updated README.md to use https in the vulnpy git clone url

---

src/vulnpy/trigger/sqli.py

Using a single database connection for the entire application lifetime is fairly irresponsible and unrealistic. This PR creates a new database connection for each call to a trigger in the sqli module.

Stop using a single persistent database connection

---

apps/aiohttp_app.py
src/vulnpy/aiohttp/vulnerable_routes.py

Add Contrast to aiohttp app. Because of our generic way of defining vulnpy routes, I had to set the function name for each route function so they don't all get named the same.

vulnpy aio routes rename func

---

setup.py

Using <0.76 because =< was not allowing for micro version install other than 0

up fastapi to support 0.75.1

---

src/vulnpy/wsgi/app.py

Makes vulnpy's WSGI app vulnerable to a bad HSTS response header.

PYT-2389 Add insecure Strict-Transport-Security header

---

setup.py
tests/requirements.txt

Added werkzeug 2.2.x to requirements

---

apps/django_app.py

Making this request `http://localhost:8000/vulnpy/deserialization/pickle-load/?user_input=testinput` will cause the django debug template to render

PYT-2593 enable django debug when standing up vulnpy live

---

apps/flask_app.py
apps/templates/jinja/xss.html

* Adds a route to the flask app that includes a reflected XSS vulnerability using `jinja` templates
* This does not include a change to vulnpy itself since it would be difficult to support across all frameworks

Add jinja template xss to flask app

---

.github/workflows/main.yml
setup.py
src/vulnpy/django/vulnerable_asgi.py

PYT-3038 update flask version to latest

---

apps/bottle_app.py
tests/bottle/test_vulnerable.py

Bottle 0.13.0 requires Bottle instances to be initialized with keyword arguments only. Previously, we were using a positional argument. This usage was wrong (passing the __name__ string as a catchall boolean parameter), so it's removed.

fix Bottle app initialization

---

setup.py
src/vulnpy/falcon/vulnerable.py
tests/falcon/test_vulnerable.py
tests/falcon/test_vulnerable_asgi.py

falcon<4 doesn't support Python 3.13. Bump the requirement to allow the latest Python version.

bump falcon requirement to <5
