Contrast-Security-OSS/vulnpy

.coveragerc, .github/workflows/main.yml, .gitignore, README.md, src/vulnpy/django/__init__.py, src/vulnpy/django/vulnerable.py, tests/django/test_vulnerable.py, tests/falcon/test_vulnerable.py, tests/flask/test_blueprint.py, tox.ini
- added public api for django app integration
- added combined coverage: now aggregate coverage must be 100% after running pytest with all python versions
- made a few minor changes to the test suite structure
=> Initial Django setup

setup.py, src/vulnpy/django/vulnerable.py, src/vulnpy/falcon/vulnerable.py, src/vulnpy/flask/blueprint.py, src/vulnpy/pyramid/vulnerable_routes.py, src/vulnpy/templates/deserialization.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/deserialization.frag.html, src/vulnpy/templates/home.html, src/vulnpy/trigger/deserialization.py, tests/django/test_vulnerable.py, tests/falcon/test_vulnerable.py, tests/flask/test_blueprint.py, tests/pyramid/test_vulnerable_routes.py, tests/requirements.txt, tox.ini
Adding triggers for:
pickle.load / loads
yaml.load / load_all
Most of the code is boilerplate and totally relies on @lazorchakp 's awesome setup. Very next PR should be about using some sort of meta-programming or AST re-writing to be able to automate generation of view definitions, url registration, and tests for every framework.
=> Pyt 999 deserialization

setup.py, src/vulnpy/templates/cmdi.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/unsafe_code_exec.frag.html, src/vulnpy/templates/home.html, src/vulnpy/templates/unsafe_code_exec.html, src/vulnpy/trigger/unsafe_code_exec.py, tests/django/test_vulnerable.py, tests/falcon/test_vulnerable.py, tests/flask/test_blueprint.py, tests/pyramid/test_vulnerable_routes.py, tests/trigger/test_unsafe_code_exec.py
Pretty self-explanatory. Thanks for all the hard work and great documentation!
=> Add triggers for unsafe-code-execution

.github/workflows/main.yml, CONTRIBUTING.md, setup.py, src/vulnpy/templates/deserialization.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/xxe.frag.html, src/vulnpy/templates/home.html, src/vulnpy/templates/xxe.html, src/vulnpy/trigger/xxe.py, tests/django/test_vulnerable.py, tests/falcon/test_vulnerable.py, tests/flask/test_blueprint.py, tests/pyramid/test_vulnerable_routes.py
Adding new XXE vulnerability triggers for lxml, xml.sax, and xml.dom. 
With the new automation, it took me 20mins or so to add all of this! 🥳
=> XXE Triggers

.coveragerc, .flake8, CONTRIBUTING.md, setup.py, src/vulnpy/templates/cmdi.html, src/vulnpy/templates/deserialization.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/hash.frag.html, src/vulnpy/templates/fragments/rand.frag.html, src/vulnpy/templates/fragments/xss.frag.html, src/vulnpy/templates/hash.html, src/vulnpy/templates/home.html, src/vulnpy/templates/pt.html, src/vulnpy/templates/rand.html, src/vulnpy/templates/unsafe_code_exec.html, src/vulnpy/templates/xss.html, src/vulnpy/trigger/__init__.py, src/vulnpy/trigger/hash.py, src/vulnpy/trigger/rand.py, src/vulnpy/vendor/six.py, tests/falcon/test_vulnerable.py, tests/trigger/test_deserialization.py, tests/trigger/test_hash.py, tests/trigger/test_pt.py, tests/trigger/test_rand.py, tox.ini
- Adds insecure hash algorithms and insecure randomizers.
- I also vendored `six` here - I needed it, and it's so easy to do that I'd prefer it over the dependency.
- I had a little fun playing around with random seeding differences in PY2 / PY3
=> Add insecure hashers / randomizers

Makefile, README.md, src/vulnpy/templates/cmdi.html, src/vulnpy/templates/deserialization.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/ssrf.frag.html, src/vulnpy/templates/hash.html, src/vulnpy/templates/home.html, src/vulnpy/templates/pt.html, src/vulnpy/templates/rand.html, src/vulnpy/templates/ssrf.html, src/vulnpy/templates/unsafe_code_exec.html, src/vulnpy/templates/xss.html, src/vulnpy/templates/xxe.html, src/vulnpy/trigger/__init__.py, src/vulnpy/trigger/ssrf.py, tests/trigger/test_ssrf.py
- Adds SSRF
- There are a lot of triggers for SSRF
- I kept in some "safe" triggers because we currently have apptest for these cases too
- Previously, we had mocked out a critical function that actually causes a real network request to be sent. Is it irresponsible not to do this? We end up firing around a dozen requests to example.com whenever we run the unit tests locally (x5 for the pipelines). I feel like this is alright, and in the spirit of the project I'd prefer if this vulnerability was "real" in the sample webapps. Lmk what you think about this
=> PYT-1003 Add SSRF

.github/workflows/codeql-analysis.yml, .github/workflows/ossar_analysis.yaml
Adding 2 security analysis tools which will scan vulnpy!
=> Add security analysis tools

src/vulnpy/templates/cmdi.html, src/vulnpy/templates/deserialization.html, src/vulnpy/templates/fragments/base.html, src/vulnpy/templates/fragments/redos.frag.html, src/vulnpy/templates/hash.html, src/vulnpy/templates/home.html, src/vulnpy/templates/rand.html, src/vulnpy/templates/redos.html, src/vulnpy/templates/sqli.html, src/vulnpy/templates/ssrf.html, src/vulnpy/templates/unsafe_code_exec.html, src/vulnpy/templates/xss.html, src/vulnpy/templates/xxe.html, src/vulnpy/trigger/__init__.py, src/vulnpy/trigger/redos.py
Adding vulnpy support for ReDOS triggers.
=> add redos triggers

src/vulnpy/templates/fragments/redos.frag.html, src/vulnpy/templates/redos.html, src/vulnpy/trigger/redos.py, tests/trigger/test_redos.py
=> add more redos triggers

apps/bottle_app.py, apps/django_app.py, apps/falcon_app.py, apps/flask_app.py, apps/pyramid_app.py, apps/wsgi_app.py
1. Add Contrast to Bottle
2. Update some Contrast imports to new style
I tested via "make framework" to see that contrast does indeed show up.
=> update some contrast imports

src/vulnpy/wsgi/app.py
This update successfully makes the wsgi app vulnerable to cache-controls-missing
=> update wsgi headers for cache control

Makefile, setup.py
This command is required in order to run our falcon app with uwsgi.
=> PYT-1318 added option to Makefile to run falcon app with uwsgi

apps/falcon_app.py
This new view will be used to assert threading functionality works as expected. Companion private PR will be shared.
=> add falcon thread view

apps/falcon_app.py
Add more contrast checks to the thread view. Used only for Contrast internal testing.
=> check protect in thread

Makefile, apps/flask_two_apps.py, apps/wsgi_two_apps.py
Add a wsgi and a flask "two apps" scenario for testing
=> Pyt 1626 two apps

Makefile, setup.py
falcon was giving us more problems than it was worth. This changes the uwsgi demo app to use flask instead
=> Change uwsgi framework to flask

Makefile
Adds a note about falcon routing. We use a strange routing implementation in order to save time when adding new endpoints
=> Add note about falcon routing

Makefile, README.md, apps/fastapi_app.py, src/vulnpy/fastapi/__init__.py, src/vulnpy/fastapi/vulnerable.py, tests/fastapi/test_vulnerable.py, tests/requirements.txt
Make initial fastapi app work with make and add auto-generated routes.
=> Pyt 1684 fastapi

apps/fastapi_app.py, setup.py
Endpoint to receive files so it could be tested from the agent
=> PYT-1752 FastAPI: test extract body with large response body

.secrets.baseline, MANIFEST.in
Product Security is having us add a pre-commit hook to check we aren't committing secrets. This PR adds the baseline file.
=> PYT-1864 added secrets baseline

setup.py
Pyramid has a new version (2.0) . We need to test that to claim support for it.
=> PYT-1860 Add testing for pyramid 2.0

apps/fastapi_app.py
Updates the file upload route in the FastAPI sample app
- makes the route properly vulnerable to command injection
- simplifies logic
- internal companion PR: https://github.com/Contrast-Security-Inc/python-agent/pull/799
=> PYT-1775 Update fastapi app for file upload source

apps/pyramid_app.py
Removed the old style pyramid middleware in favour of the new WSGI middleware.
=> PYT-1108 Remove old Pyramid middleware

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/ossar_analysis.yaml, setup.py, src/vulnpy/trigger/deserialization.py, tests/falcon/test_vulnerable.py, tox.ini
Bumped pyyaml to the latest released version.
=> PYT-1807 Bump pyyaml dependency to latest

setup.py
=> PYT-1992 Upped fastapi to 0.71

src/vulnpy/aiohttp/vulnerable_routes.py, tests/aiohttp/test_vulnerable_async.py
This is changed only for the sake that integration tests test without the slash and the redirection doesn't work properly. They were failing with ` path not found`
=> PYT-1905 AioHTTP integration tests route change

setup.py
=> PYT-2003 Upped FastAPI version to 0.73

setup.py
=> allow aiohttp install < 4

Makefile, apps/django_app.py
=> Fix django app not calling contrast middleware

Makefile, apps/quart_app.py, setup.py, src/vulnpy/quart/__init__.py, src/vulnpy/quart/blueprint.py, src/vulnpy/trigger/xpath.py, tests/quart/test_blueprint.py, tox.ini
This PR adds all necessary code to be able to stand a quart app via `make quart`
I tested a few home and trigger views and it all looks good.
- [x ] We do not want to update to this PR's top commit. **not necessary at this time**
=> Pyt 2040 add quart app

setup.py
=> allow fastapi 0.74

setup.py, src/vulnpy/django/vulnerable.py
=> PYT-2103 Add Django 4 Framework Test

apps/quart_app.py, setup.py
- [ x] I've created a PR to update the vulnpy commit
=> add contrast to quart

apps/quart_app.py, tox.ini
=> add file upload route to quart

setup.py
=> up fastapi version

Makefile, apps/falcon_asgi_app.py, src/vulnpy/falcon/__init__.py, src/vulnpy/falcon/vulnerable_asgi.py, tests/falcon/test_vulnerable_asgi.py
Adding a falcon application using asgi routes.
- [x ] We do not want to update to this PR's top commit. not at this time
=> add falcon asgi app

Makefile, setup.py
added uvicorn extra dependencies and updated falcon-asgi to just falcon-uvicorn for easier testing.
=> Uvicorn for falcon

apps/falcon_asgi_app.py
=> add contrast to falcon asgi

setup.py
- [x ] I've created a PR to update the vulnpy commit **forthcoming**
=> specify supported uvicorn version

Makefile, apps/django_asgi_app.py, pyproject.toml, src/vulnpy/django/__init__.py, src/vulnpy/django/vulnerable_asgi.py, tests/django/test_vulnerable_asgi.py, tests/falcon/test_vulnerable_asgi.py
=> PYT-2143: Django Async Add VulnPy App

apps/django_asgi_app.py
=> PYT-2143: Uncommented code for contrast middleware

setup.py, tests/requirements.txt
=> bump fastapi allowed version

setup.py
Pin werkzeug for flask and quart
=> pin Werkzeug

setup.py
- [ x] I've created a PR to update the vulnpy commit
=> Upgrade fastapi req to .84

setup.py
=> Upgrade fastapi req to .85

Makefile
=> Add `--honour-stdin` option to make uwsgi debugging easier

setup.py
=> PYT-2428 update setup.py to install quart version <1

setup.py
- I need this for my current work, so there will be an agent PR eventually
=> Loosen up FastAPI requirement

.github/workflows/main.yml, Makefile, setup.py, src/vulnpy/aiohttp/vulnerable_routes.py, src/vulnpy/falcon/vulnerable.py, src/vulnpy/falcon/vulnerable_asgi.py, tests/flask/test_blueprint.py, tox.ini
Had this left over from recent work, figured it was worth merging
---
This PR now also includes some general health updates for vulnpy (PYT-2955)
=> Add trailing slash option to aiohttp routes

setup.py
I will be updating the vulnpy commit in my upcoming agent PR.
=> Pin aiohttp to <3.11
